# Generated by Django 6.0.3 on 2026-04-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroTechPill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Технология (hero)",
                "verbose_name_plural": "Технологии (hero)",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("commerce", "E-commerce"),
                            ("data", "Data-driven"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Например: Django, DRF, PostgreSQL",
                        max_length=500,
                        verbose_name="Теги через запятую",
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True, verbose_name="Демо / Live")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Приветствие (hero)"
                    ),
                ),
                (
                    "hero_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Имя в шапке и hero"
                    ),
                ),
                (
                    "hero_tagline",
                    models.TextField(
                        blank=True, verbose_name="Подзаголовок / описание (meta)"
                    ),
                ),
                (
                    "hero_role",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Роль / стек одной строкой",
                    ),
                ),
                (
                    "code_block",
                    models.TextField(
                        blank=True,
                        help_text="Многострочный текст; HTML экранируется — используйте обычный код.",
                        verbose_name="Код в блоке справа",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок «Обо мне»"
                    ),
                ),
                (
                    "about_lead",
                    models.TextField(blank=True, verbose_name="Лид «Обо мне»"),
                ),
                (
                    "about_body",
                    models.TextField(
                        blank=True,
                        help_text="Основной абзац; переносы строк сохраняются.",
                        verbose_name="Текст «Обо мне»",
                    ),
                ),
                (
                    "m1_value",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Метрика 1 — число"
                    ),
                ),
                (
                    "m1_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Метрика 1 — подпись"
                    ),
                ),
                (
                    "m2_value",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Метрика 2 — число"
                    ),
                ),
                (
                    "m2_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Метрика 2 — подпись"
                    ),
                ),
                (
                    "m3_value",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Метрика 3 — число"
                    ),
                ),
                (
                    "m3_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Метрика 3 — подпись"
                    ),
                ),
                (
                    "stack_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок «Стек»"
                    ),
                ),
                ("stack_lead", models.TextField(blank=True, verbose_name="Лид «Стек»")),
                (
                    "projects_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок «Проекты»"
                    ),
                ),
                (
                    "projects_lead",
                    models.TextField(blank=True, verbose_name="Лид «Проекты»"),
                ),
                (
                    "contact_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок «Контакты»"
                    ),
                ),
                (
                    "contact_lead",
                    models.TextField(blank=True, verbose_name="Лид «Контакты»"),
                ),
                (
                    "contact_email",
                    models.CharField(
                        blank=True,
                        help_text="Текст ссылки, например hello@mail.com",
                        max_length=200,
                        verbose_name="Email (отображение)",
                    ),
                ),
                (
                    "contact_email_href",
                    models.CharField(
                        blank=True,
                        help_text="Например mailto:hello@mail.com",
                        max_length=300,
                        verbose_name="Email (mailto)",
                    ),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                (
                    "case_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Кейс: заголовок"
                    ),
                ),
                (
                    "case_problem",
                    models.TextField(blank=True, verbose_name="Кейс: проблема"),
                ),
                (
                    "case_solution",
                    models.TextField(blank=True, verbose_name="Кейс: решение"),
                ),
                (
                    "case_result",
                    models.TextField(blank=True, verbose_name="Кейс: результат"),
                ),
                (
                    "header_logo_label",
                    models.CharField(
                        blank=True,
                        help_text="Если пусто — используется имя из hero.",
                        max_length=120,
                        verbose_name="Текст логотипа в шапке",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тексты сайта",
                "verbose_name_plural": "Тексты сайта",
            },
        ),
        migrations.CreateModel(
            name="StackGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Группа стека",
                "verbose_name_plural": "Группы стека",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "hint",
                    models.TextField(
                        blank=True,
                        help_text="Для расширенной вёрстки; на простой странице можно кратко.",
                        verbose_name="Описание при наведении",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("advanced", "Advanced"),
                            ("proficient", "Proficient"),
                            ("intermediate", "Intermediate"),
                        ],
                        default="proficient",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="portfolio.stackgroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент стека",
                "verbose_name_plural": "Элементы стека",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
