# Generated by Django 6.0.3 on 2026-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_seed_site_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "issuer",
                    models.CharField(
                        max_length=200, verbose_name="Выдавшая организация"
                    ),
                ),
                ("date", models.CharField(max_length=50, verbose_name="Дата / год")),
                (
                    "credential_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ID сертификата"
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        default="🎯", max_length=10, verbose_name="Emoji-бейдж"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="Например: M.Sc., B.Sc.",
                        max_length=50,
                        verbose_name="Степень",
                    ),
                ),
                ("field", models.CharField(max_length=200, verbose_name="Направление")),
                (
                    "institution",
                    models.CharField(max_length=200, verbose_name="Учебное заведение"),
                ),
                ("period", models.CharField(max_length=100, verbose_name="Период")),
                (
                    "gpa",
                    models.CharField(blank=True, max_length=50, verbose_name="GPA"),
                ),
                (
                    "thesis",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Тема диплома / thesis"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образование",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200, verbose_name="Должность")),
                ("company", models.CharField(max_length=200, verbose_name="Компания")),
                (
                    "period",
                    models.CharField(
                        help_text="Например: 2021 – Present",
                        max_length=100,
                        verbose_name="Период",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Локация"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        default="full-time",
                        max_length=20,
                        verbose_name="Тип занятости",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "achievements",
                    models.TextField(
                        blank=True,
                        help_text="По одному на строку — каждая строка станет пунктом списка.",
                        verbose_name="Достижения",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Теги через запятую"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Опыт работы",
                "verbose_name_plural": "Опыт работы",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="Featured"),
        ),
        migrations.AddField(
            model_name="project",
            name="long_description",
            field=models.TextField(blank=True, verbose_name="Развёрнутое описание"),
        ),
        migrations.AddField(
            model_name="project",
            name="stars",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Stars (отображение)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Production", "Production"),
                    ("Research", "Research"),
                    ("Open Source", "Open Source"),
                    ("WIP", "WIP"),
                ],
                default="Production",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="twitter_url",
            field=models.URLField(blank=True, verbose_name="Twitter / X"),
        ),
        migrations.AddField(
            model_name="stackgroup",
            name="icon",
            field=models.CharField(
                default="💻", max_length=10, verbose_name="Emoji-иконка"
            ),
        ),
        migrations.AddField(
            model_name="stackitem",
            name="level_percent",
            field=models.PositiveIntegerField(
                default=75,
                help_text="0–100, используется для прогресс-бара на сайте.",
                verbose_name="Уровень (%)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(default="Other", max_length=60),
        ),
    ]
